"""add fee and tax  to payment

Revision ID: 085a6505217a
Revises: b3779e9ec65a
Create Date: 2026-02-25 03:13:44.843271

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '085a6505217a'
down_revision: Union[str, Sequence[str], None] = 'b3779e9ec65a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payment', sa.Column('fee', sa.Float(), nullable=False))
    op.add_column('payment', sa.Column('tax', sa.Float(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('payment', 'tax')
    op.drop_column('payment', 'fee')
    # ### end Alembic commands ###
