"""add updated_at and created_at  to multiple tables

Revision ID: 13eb081aa39c
Revises: 197e4c923abb
Create Date: 2026-02-24 03:35:09.112150

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '13eb081aa39c'
down_revision: Union[str, Sequence[str], None] = '197e4c923abb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('address', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('address', sa.Column('updated_at', sa.DateTime(), nullable=False))
    op.add_column('cart', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('cart', sa.Column('updated_at', sa.DateTime(), nullable=False))
    op.add_column('order', sa.Column('updated_at', postgresql.TIMESTAMP(), nullable=True))
    op.add_column('order_item', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('order_item', sa.Column('updated_at', sa.DateTime(), nullable=False))
    op.add_column('payment', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('payment', sa.Column('updated_at', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('payment', 'updated_at')
    op.drop_column('payment', 'created_at')
    op.drop_column('order_item', 'updated_at')
    op.drop_column('order_item', 'created_at')
    op.drop_column('order', 'updated_at')
    op.drop_column('cart', 'updated_at')
    op.drop_column('cart', 'created_at')
    op.drop_column('address', 'updated_at')
    op.drop_column('address', 'created_at')
    # ### end Alembic commands ###
