"""add seller_id to product

Revision ID: 197e4c923abb
Revises: 3d85cd3eab8b
Create Date: 2026-02-19 04:01:27.612259

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '197e4c923abb'
down_revision: Union[str, Sequence[str], None] = '3d85cd3eab8b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('seller_id', sa.Uuid(), nullable=False))
    op.create_foreign_key(None, 'product', 'seller', ['seller_id'], ['uid'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'product', type_='foreignkey')
    op.drop_column('product', 'seller_id')
    # ### end Alembic commands ###
