"""add phone and total_saller to seller

Revision ID: 51dedd99c9c3
Revises: 882e26260dd5
Create Date: 2026-02-18 04:27:41.736584

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '51dedd99c9c3'
down_revision: Union[str, Sequence[str], None] = '882e26260dd5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('seller', sa.Column('phone', sa.VARCHAR(), nullable=False))
    op.add_column('seller', sa.Column('total_saller', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('seller', 'total_saller')
    op.drop_column('seller', 'phone')
    # ### end Alembic commands ###
