"""Add   seller_request_status to Customer

Revision ID: 7e68d77e9f10
Revises: 51dedd99c9c3
Create Date: 2026-02-18 04:44:28.377731

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '7e68d77e9f10'
down_revision: Union[str, Sequence[str], None] = '51dedd99c9c3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customer', sa.Column('seller_request_status', sa.VARCHAR(), nullable=False, server_default='none'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('customer', 'seller_request_status')
    # ### end Alembic commands ###
