"""add foreign key to payment.customer_id

Revision ID: 882e26260dd5
Revises: 517b629c9baf
Create Date: 2026-02-17 22:04:53.573146

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '882e26260dd5'
down_revision: Union[str, Sequence[str], None] = '517b629c9baf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'address', 'customer', ['cutomer_id'], ['uid'])
    op.create_foreign_key(None, 'cart', 'customer', ['customer_id'], ['uid'])
    op.add_column('customer', sa.Column('hashed_password', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.alter_column('customer', 'AGE',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('customer', 'is_verified',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('customer', 'DataOfBirth',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.drop_column('customer', 'hassed_password')
    op.create_foreign_key(None, 'order', 'customer', ['customer_id'], ['uid'])
    op.add_column('payment', sa.Column('customer_id', sa.Uuid(), nullable=False))
    op.alter_column('payment', 'order_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.create_foreign_key(None, 'payment', 'customer', ['customer_id'], ['uid'])
    op.add_column('product', sa.Column('mrp', sa.Float(), nullable=False))
    op.add_column('product', sa.Column('brand', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('product', sa.Column('category_id', sa.Uuid(), nullable=True))
   
    op.alter_column('product', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('product', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.create_foreign_key(None, 'product', 'category', ['category_id'], ['uid'])
    op.drop_column('product', 'MRP')
    op.drop_column('product', 'Brand')
    op.create_foreign_key(None, 'review', 'customer', ['customer_id'], ['uid'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'review', type_='foreignkey')
    op.add_column('product', sa.Column('Brand', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('product', sa.Column('MRP', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'product', type_='foreignkey')
    op.alter_column('product', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('product', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    
    op.drop_column('product', 'category_id')
    op.drop_column('product', 'brand')
    op.drop_column('product', 'mrp')
    op.drop_constraint(None, 'payment', type_='foreignkey')
    op.alter_column('payment', 'order_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_column('payment', 'customer_id')
    op.drop_constraint(None, 'order', type_='foreignkey')
    op.add_column('customer', sa.Column('hassed_password', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.alter_column('customer', 'DataOfBirth',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('customer', 'is_verified',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('customer', 'AGE',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('customer', 'hashed_password')
    op.drop_constraint(None, 'cart', type_='foreignkey')
    op.drop_constraint(None, 'address', type_='foreignkey')
    # ### end Alembic commands ###
