"""add transaction_id and amount to payment

Revision ID: b3779e9ec65a
Revises: 5c11200b5978
Create Date: 2026-02-25 02:45:10.846146

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b3779e9ec65a'
down_revision: Union[str, Sequence[str], None] = '5c11200b5978'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payment', sa.Column('amount', sa.Float(), nullable=False))
    op.add_column('payment', sa.Column('transaction_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.alter_column('payment', 'status',
               existing_type=postgresql.ENUM('success', 'failed', 'pending', name='payment_status_enum'),
               nullable=True,
               existing_server_default=sa.text("'pending'::payment_status_enum"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('payment', 'status',
               existing_type=postgresql.ENUM('success', 'failed', 'pending', name='payment_status_enum'),
               nullable=False,
               existing_server_default=sa.text("'pending'::payment_status_enum"))
    op.drop_column('payment', 'transaction_id')
    op.drop_column('payment', 'amount')
    # ### end Alembic commands ###
