"""update seller table

Revision ID: b7612e57cd59
Revises: 7e68d77e9f10
Create Date: 2026-02-18 14:38:29.859993

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b7612e57cd59'
down_revision: Union[str, Sequence[str], None] = '7e68d77e9f10'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('seller', sa.Column('customer_id', sa.Uuid(), nullable=False))
    op.add_column('seller', sa.Column('store_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('seller', sa.Column('rating', sa.Float(), nullable=False))
    op.add_column('seller', sa.Column('total_sales', sa.Integer(), nullable=False))
    op.alter_column('seller', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('seller', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.create_unique_constraint(None, 'seller', ['customer_id'])
    op.create_foreign_key(None, 'seller', 'customer', ['customer_id'], ['uid'])
    op.drop_column('seller', 'email')
    op.drop_column('seller', 'name')
    op.drop_column('seller', 'total_saller')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('seller', sa.Column('total_saller', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('seller', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('seller', sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'seller', type_='foreignkey')
    op.drop_constraint(None, 'seller', type_='unique')
    op.alter_column('seller', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('seller', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.drop_column('seller', 'total_sales')
    op.drop_column('seller', 'rating')
    op.drop_column('seller', 'store_name')
    op.drop_column('seller', 'customer_id')
    # ### end Alembic commands ###
